spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-basic;
    username: sa
    password:
    driverClassName: org.h2.Driver
